version: '3.3'
services:
 web:
    build: .
    container_name: nodeOrdinario
    depends_on:
    - basededatos
    volumes:
    - .:/usr/src/app
    ports:
    - 3000:3000
    
 basededatos:
  image: mysql:latest
  container_name: bdmysql
  command: --default-authentication-plugin=mysql_native_password
  restart: always
  environment:
   MYSQL_ROOT_PASSWORD: r00t
   MYSQL_DATABASE: abarrotes
   MYSQL_USER: root
   MYSQL_PASSWORD: r00t
  ports:
   - '3006:3006'
  expose:
    - '3306'
  volumes:
   - .:/practica
  command: --init-file="/practica/abarrotes.sql"
