version: '3.3'
services:
  web:
    build: .
    container_name: nodeOrdinario
    depends_on:
    - db
    volumes:
    - .:/usr/src/app
    ports:
    - 3000:3000
  db:
    image: mysql:5.7
    restart: always
    environment:
     MYSQL_ROOT_PASSWORD: r00t
     MYSQL_DATABASE: abarrotes
     MYSQL_USER: root
     MYSQL_PASSWORD: r00t
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - .:/practica
    command: --init-file="/practica/abarrotes.sql"
# Names our volume
volumes:
  my-db: